sudo: required

services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=georgema/terraform-aws-cli

script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -t terraform-aws-cli -t $REPO:$TAG -f Dockerfile .
